//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabDBEntities : DbContext
    {
        public LabDBEntities()
            : base("name=LabDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aspect> Aspects1 { get; set; }
        public virtual DbSet<Batch> Batches1 { get; set; }
        public virtual DbSet<Colour> Colours1 { get; set; }
        public virtual DbSet<Construction> Constructions1 { get; set; }
        public virtual DbSet<ControlPlan> ControlPlans { get; set; }
        public virtual DbSet<external_constructions> external_constructions { get; set; }
        public virtual DbSet<ExternalReport> ExternalReports { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<Master> Masters1 { get; set; }
        public virtual DbSet<Material> Materials1 { get; set; }
        public virtual DbSet<Method> Methods1 { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<PendingTest> PendingTests { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<RequestedReports> RequestedReports { get; set; }
        public virtual DbSet<Requirement> Requirements1 { get; set; }
        public virtual DbSet<SampleLogEntry> SampleLogEntries { get; set; }
        public virtual DbSet<SpecificationVersion> SpecificationVersions { get; set; }
        public virtual DbSet<Specification> Specifications1 { get; set; }
        public virtual DbSet<Standard> Standards1 { get; set; }
        public virtual DbSet<SubRequirement> SubRequirements { get; set; }
        public virtual DbSet<SubTest> SubTests1 { get; set; }
        public virtual DbSet<Test> Tests1 { get; set; }
        public virtual DbSet<User> Users1 { get; set; }
        public virtual DbSet<ReportFiles> ReportFiles { get; set; }
    }
}
