//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingTest
    {
        public long ID { get; set; }
        public string deletion_flag { get; set; }
        public long requestID { get; set; }
        public long requirementID { get; set; }
        public string notes { get; set; }
    
        public virtual RequestedReports RequestedReport { get; set; }
        public virtual Requirement Requirement { get; set; }
    }
}
