//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public long ID { get; set; }
        public string deletion_flag { get; set; }
        public long authorID { get; set; }
        public long batchID { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string end_date { get; set; }
        public Nullable<long> number { get; set; }
        public long projectID { get; set; }
        public Nullable<long> specificationID { get; set; }
        public Nullable<long> specification_versionID { get; set; }
        public string start_date { get; set; }
        public Nullable<long> requestID { get; set; }
        public string fileID { get; set; }
        public string label { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Person Author { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
        public virtual RequestedReports RequestedReport { get; set; }
    }
}
