//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestedReports()
        {
            this.PendingTests = new HashSet<PendingTest>();
            this.Reports = new HashSet<Report>();
        }
    
        public long ID { get; set; }
        public Nullable<long> deletion_flag { get; set; }
        public Nullable<long> requesterID { get; set; }
        public long projectID { get; set; }
        public long specification_versionID { get; set; }
        public long batchID { get; set; }
        public Nullable<long> reportID { get; set; }
        public string notes { get; set; }
        public Nullable<long> progress { get; set; }
        public Nullable<long> priority_modifier { get; set; }
        public Nullable<long> pipeline_order { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual SpecificationVersion SpecificationVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PendingTest> PendingTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
