//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleLogEntry
    {
        public long ID { get; set; }
        public long batchID { get; set; }
        public string code { get; set; }
        public string date { get; set; }
    
        public virtual Batch Batch { get; set; }
    }
}
