//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Standard()
        {
            this.Specifications = new HashSet<Specification>();
            this.Methods = new HashSet<Method>();
        }
    
        public long ID { get; set; }
        public string deletion_flag { get; set; }
        public string name { get; set; }
        public string issue { get; set; }
        public Nullable<long> organizationID { get; set; }
        public Nullable<long> old_flag { get; set; }
        public string fileID { get; set; }
        public Nullable<long> previous_issueID { get; set; }
        public Nullable<long> next_issueID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specification> Specifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Method> Methods { get; set; }
    }
}
