//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTest
    {
        public long ID { get; set; }
        public string deletion_flag { get; set; }
        public long sub_requirementID { get; set; }
        public string result { get; set; }
        public long testID { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual SubRequirement SubRequirement { get; set; }
    }
}
