//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long ID { get; set; }
        public string full_name { get; set; }
        public string hashed_password { get; set; }
        public string role_list { get; set; }
        public string user_name { get; set; }
        public long personID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
