// <auto-generated />
using System;
using LInst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LInst.Migrations
{
    [DbContext(typeof(LInstContext))]
    [Migration("20181128153623_CreateLInstDb_2")]
    partial class CreateLInstDb_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("LInst.CalibrationFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CalibrationReportID");

                    b.Property<string>("Path");

                    b.HasKey("ID");

                    b.HasIndex("CalibrationReportID");

                    b.ToTable("CalibrationFiles");
                });

            modelBuilder.Entity("LInst.CalibrationReport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CalibrationResultID");

                    b.Property<int>("InstrumentID");

                    b.Property<int>("LaboratoryID");

                    b.Property<string>("Notes");

                    b.Property<int>("Number");

                    b.Property<int?>("TechID");

                    b.Property<int>("Year");

                    b.HasKey("ID");

                    b.HasIndex("CalibrationResultID");

                    b.HasIndex("InstrumentID");

                    b.HasIndex("LaboratoryID");

                    b.HasIndex("TechID");

                    b.ToTable("CalibrationReports");
                });

            modelBuilder.Entity("LInst.CalibrationResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("CalibrationResults");
                });

            modelBuilder.Entity("LInst.Instrument", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CalibrationDueDate");

                    b.Property<int?>("CalibrationInterval");

                    b.Property<int?>("CalibrationResponsibleID");

                    b.Property<string>("Code");

                    b.Property<string>("Description");

                    b.Property<int>("InstrumentTypeID");

                    b.Property<bool>("IsInService");

                    b.Property<bool>("IsUnderControl");

                    b.Property<int?>("ManufacturerID");

                    b.Property<string>("Model");

                    b.Property<string>("SerialNumber");

                    b.Property<int?>("SupplierID");

                    b.Property<int>("UtilizationAreaID");

                    b.HasKey("ID");

                    b.HasIndex("CalibrationResponsibleID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("LInst.InstrumentFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InstrumentID");

                    b.Property<string>("Path");

                    b.HasKey("ID");

                    b.HasIndex("InstrumentID");

                    b.ToTable("InstrumentFiles");
                });

            modelBuilder.Entity("LInst.InstrumentMaintenanceEvent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("InstrumentID");

                    b.Property<int?>("TechID");

                    b.HasKey("ID");

                    b.HasIndex("InstrumentID");

                    b.HasIndex("TechID");

                    b.ToTable("InstrumentMaintenanceEvents");
                });

            modelBuilder.Entity("LInst.InstrumentProperty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InstrumentID");

                    b.Property<bool>("IsCalibrationProperty");

                    b.Property<string>("Name");

                    b.Property<int>("Value");

                    b.HasKey("ID");

                    b.HasIndex("InstrumentID");

                    b.ToTable("InstrumentProperties");
                });

            modelBuilder.Entity("LInst.InstrumentType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("InstrumentTypes");
                });

            modelBuilder.Entity("LInst.InstrumentUtilizationArea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Plant");

                    b.HasKey("ID");

                    b.ToTable("InstrumentUtilizationAreas");
                });

            modelBuilder.Entity("LInst.Organization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("LInst.OrganizationRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("OrganizationRoles");
                });

            modelBuilder.Entity("LInst.OrganizationRoleMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsSelected");

                    b.Property<int>("OrganizationID");

                    b.Property<int>("OrganizationRoleID");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("OrganizationRoleID");

                    b.ToTable("OrganizationRoleMappings");
                });

            modelBuilder.Entity("LInst.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("LInst.PersonRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("PersonRoles");
                });

            modelBuilder.Entity("LInst.PersonRoleMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsSelected");

                    b.Property<int>("PersonID");

                    b.Property<int>("RoleID");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.HasIndex("RoleID");

                    b.ToTable("PersonRoleMappings");
                });

            modelBuilder.Entity("LInst.CalibrationFile", b =>
                {
                    b.HasOne("LInst.CalibrationReport", "CalibrationReport")
                        .WithMany()
                        .HasForeignKey("CalibrationReportID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LInst.CalibrationReport", b =>
                {
                    b.HasOne("LInst.CalibrationResult", "CalibrationResult")
                        .WithMany()
                        .HasForeignKey("CalibrationResultID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LInst.Instrument", "Instrument")
                        .WithMany("CalibrationReports")
                        .HasForeignKey("InstrumentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LInst.Organization", "Laboratory")
                        .WithMany()
                        .HasForeignKey("LaboratoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LInst.Person", "Tech")
                        .WithMany()
                        .HasForeignKey("TechID");
                });

            modelBuilder.Entity("LInst.Instrument", b =>
                {
                    b.HasOne("LInst.Organization", "CalibrationResponsible")
                        .WithMany()
                        .HasForeignKey("CalibrationResponsibleID");

                    b.HasOne("LInst.Organization", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerID");

                    b.HasOne("LInst.Organization", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID");
                });

            modelBuilder.Entity("LInst.InstrumentFile", b =>
                {
                    b.HasOne("LInst.Instrument", "Instrument")
                        .WithMany("InstrumentFiles")
                        .HasForeignKey("InstrumentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LInst.InstrumentMaintenanceEvent", b =>
                {
                    b.HasOne("LInst.Instrument", "Instrument")
                        .WithMany("MaintenanceEvents")
                        .HasForeignKey("InstrumentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LInst.Person", "Tech")
                        .WithMany()
                        .HasForeignKey("TechID");
                });

            modelBuilder.Entity("LInst.InstrumentProperty", b =>
                {
                    b.HasOne("LInst.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LInst.OrganizationRoleMapping", b =>
                {
                    b.HasOne("LInst.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LInst.OrganizationRole", "OrganizationRole")
                        .WithMany()
                        .HasForeignKey("OrganizationRoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LInst.PersonRoleMapping", b =>
                {
                    b.HasOne("LInst.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LInst.PersonRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
