//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasurementUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeasurementUnit()
        {
            this.InstrumentMeasurableProperties = new HashSet<InstrumentMeasurableProperty>();
            this.calibration_report_measurable_property_mappings = new HashSet<CalibrationReportInstrumentPropertyMapping>();
        }
    
        public int ID { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public int MeasurableQuantityID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstrumentMeasurableProperty> InstrumentMeasurableProperties { get; set; }
        public virtual MeasurableQuantity MeasurableQuantities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalibrationReportInstrumentPropertyMapping> calibration_report_measurable_property_mappings { get; set; }
    }
}
