//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRoleMapping
    {
        public int ID { get; set; }
        public int personID { get; set; }
        public int roleID { get; set; }
        public bool IsSelected { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PersonRole Role { get; set; }
    }
}
