//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserD()
        {
            this.RoleMappings = new HashSet<UserRoleMappingD>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string HashedPassword { get; set; }
        public string UserName { get; set; }
        public Nullable<int> PersonID { get; set; }
    
        public virtual PersonD Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleMappingD> RoleMappings { get; set; }
    }
}
