//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleMapping
    {
        public int ID { get; private set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public bool IsSelected { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual User User { get; set; }
    }
}
