//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.Reports = new HashSet<Report>();
            this.SampleLogEntries = new HashSet<SampleLogEntry>();
            this.RequestedReports = new HashSet<RequestedReports>();
        }
    
        public long ID { get; set; }
        public string deletion_flag { get; set; }
        public string number { get; set; }
        public string trial_area { get; set; }
        public string notes_1 { get; set; }
        public string notes_2 { get; set; }
        public string structure { get; set; }
        public string actions { get; set; }
        public string conclusion { get; set; }
        public long materialID { get; set; }
        public Nullable<long> fileID { get; set; }
    
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleLogEntry> SampleLogEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestedReports> RequestedReports { get; set; }
    }
}
