//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationReportInstrumentPropertyMapping
    {
        public int ID { get; set; }
        public int CalibrationReportID { get; set; }
        public int MeasurablePropertyID { get; set; }
        public double UpperRangeValue { get; set; }
        public double LowerRangeValue { get; set; }
        public double ExtendedUncertainty { get; set; }
        public CalibrationResult Result { get; set; }
        public int MeasurementUnitID { get; set; }
        public bool IsVerification { get; set; }
    
        public virtual CalibrationReport CalibrationReport { get; set; }
        public virtual InstrumentMeasurableProperty InstrumentMeasurableProperty { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
    }
}
