//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalibrationReport()
        {
            this.CalibrationFiles = new HashSet<CalibrationFiles>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Number { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public int laboratoryID { get; set; }
        public Nullable<int> referenceID { get; set; }
        public int instrumentID { get; set; }
        public string Notes { get; set; }
        public string Result { get; set; }
    
        public virtual Instrument Instrument { get; set; }
        public virtual Organization Laboratory { get; set; }
        public virtual Person Tech { get; set; }
        public virtual Instrument Reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalibrationFiles> CalibrationFiles { get; set; }
    }
}
