//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Construction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Construction()
        {
            this.Materials = new HashSet<Material>();
        }
    
        public int ID { get; set; }
        public string Line { get; set; }
        public int AspectID { get; private set; }
        public Nullable<int> ProjectID { get; private set; }
        public Nullable<int> ExternalConstructionID { get; private set; }
        public Nullable<int> TypeID { get; private set; }
    
        public virtual Aspect Aspect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ExternalConstruction ExternalConstruction { get; set; }
        public virtual Project Project { get; set; }
        public virtual MaterialType Type { get; set; }
    }
}
