//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabDB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlPlan
    {
        public long ID { get; set; }
        public string deletion_flag { get; set; }
        public string name { get; set; }
        public long specificationID { get; set; }
        public string test_plan { get; set; }
    
        public virtual Specification Specification { get; set; }
    }
}
