//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalReport
    {
        public long ID { get; set; }
        public string deletion_flag { get; set; }
        public string date { get; set; }
        public string description { get; set; }
        public string external_number { get; set; }
        public string internal_number { get; set; }
        public Nullable<long> external_labID { get; set; }
        public string material_sent { get; set; }
        public string request_done { get; set; }
        public string purchase_order { get; set; }
        public Nullable<double> price { get; set; }
        public string samples { get; set; }
        public string currency { get; set; }
        public string report_received { get; set; }
        public string fileID { get; set; }
        public long projectID { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
