//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentPropertyData
    {
        public int ID { get; set; }
        public int instrumentID { get; set; }
        public int measurable_propertyID { get; set; }
        public int umID { get; set; }
        public string range { get; set; }
        public string division { get; set; }
    
        public virtual Instrument instrument { get; set; }
        public virtual MeasurableProperty measurable_properties { get; set; }
        public virtual MeasureUnit measure_units { get; set; }
    }
}
