//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentMaintenanceEvent
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int OrganizationID { get; set; }
        public int InstrumentID { get; set; }
    
        public virtual Instrument Instrument { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
