//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrument()
        {
            this.CalibrationReports = new HashSet<CalibrationReport>();
            this.Tests = new HashSet<Test>();
            this.MaintenanceEvent = new HashSet<InstrumentMaintenanceEvent>();
            this.CalibrationReportAsReference = new HashSet<CalibrationReport>();
            this.AssociatedMethods = new HashSet<Method>();
            this.InstrumentMeasurableProperties = new HashSet<InstrumentMeasurableProperty>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int InstrumentTypeID { get; set; }
        public sbyte ControlPeriod { get; set; }
        public bool IsUnderControl { get; set; }
        public Nullable<int> supplierID { get; set; }
        public Nullable<int> manufacturerID { get; set; }
        public string SerialNumber { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> CalibrationDueDate { get; set; }
        public Nullable<int> CalibrationResponsibleID { get; set; }
        public Nullable<int> UtilizationAreaID { get; set; }
        public bool IsInService { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalibrationReport> CalibrationReports { get; set; }
        public virtual InstrumentType InstrumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
        public virtual Organization Manufacturer { get; set; }
        public virtual Organization Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstrumentMaintenanceEvent> MaintenanceEvent { get; set; }
        public virtual Organization CalibrationResponsible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalibrationReport> CalibrationReportAsReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Method> AssociatedMethods { get; set; }
        public virtual InstrumentUtilizationArea InstrumentUtilizationArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstrumentMeasurableProperty> InstrumentMeasurableProperties { get; set; }
    }
}
