//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Method
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Method()
        {
            this.Requirements = new HashSet<Requirement>();
        }
    
        public int ID { get; set; }
        private int standardID { get; set; }
        public string Measurements { get; set; }
        private int propertyID { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public string um { get; set; }
        public int CostUnits { get; set; }
        public bool IsObsolete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requirement> Requirements { get; set; }
        public virtual Property Property { get; set; }
        public virtual Std Standard { get; set; }
    }
}
