//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Method
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Method()
        {
            this.requirements = new HashSet<Requirement>();
        }
    
        public int ID { get; set; }
        public int standardID { get; set; }
        public string measurements { get; set; }
        public int propertyID { get; set; }
        public string label { get; set; }
        public string description { get; set; }
        public string um { get; set; }
        public int cost_units { get; set; }
        public bool old_flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requirement> requirements { get; set; }
        public virtual Property property { get; set; }
        public virtual Std standard { get; set; }
    }
}
