//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingTest
    {
        public long ID { get; set; }
        public string deletion_flag { get; set; }
        public long requestID { get; set; }
        public long requirementID { get; set; }
        public string notes { get; set; }
    
        public virtual RequestedReports RequestedReport { get; set; }
        public virtual Requirement Requirement { get; set; }
    }
}
