//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.report_files = new HashSet<ReportFile>();
            this.tasks = new HashSet<Task>();
            this.tests = new HashSet<Test>();
        }
    
        public int ID { get; set; }
        public int authorID { get; set; }
        public int batchID { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public int number { get; set; }
        public Nullable<int> projectID { get; set; }
        public Nullable<int> specificationID { get; set; }
        public Nullable<int> specification_versionID { get; set; }
        public string start_date { get; set; }
        public string requestID { get; set; }
        public string label { get; set; }
    
        public virtual Batch batch { get; set; }
        public virtual Person person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportFile> report_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> tests { get; set; }
        public virtual Specification specification { get; set; }
        public virtual SpecificationVersion specification_versions { get; set; }
    }
}
