//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public int ID { get; set; }
        public int BatchID { get; private set; }
        public string Code { get; set; }
        public System.DateTime Date { get; set; }
        public int personID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Person LogAuthor { get; set; }
    }
}
