//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleLogEntry
    {
        public long ID { get; set; }
        public long batchID { get; set; }
        public string code { get; set; }
        public string date { get; set; }
    
        public virtual Batch Batch { get; set; }
    }
}
