//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecificationIssue()
        {
            this.SpecificationFiles = new HashSet<SpecificationFile>();
        }
    
        public long ID { get; set; }
        public int SpecificationID { get; private set; }
        public string Issue { get; set; }
        public Nullable<int> NextIssueID { get; private set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificationFile> SpecificationFiles { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
