//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Std
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Std()
        {
            this.methods = new HashSet<Method>();
            this.specifications = new HashSet<Specification>();
            this.standard_files = new HashSet<StandardFile>();
            this.standards1 = new HashSet<Std>();
            this.standards11 = new HashSet<Std>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string issue { get; set; }
        public int organizationID { get; set; }
        public Nullable<int> old_flag { get; set; }
        public Nullable<int> fileID { get; set; }
        public Nullable<int> previous_issueID { get; set; }
        public Nullable<int> next_issueID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Method> methods { get; set; }
        public virtual Organization organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specification> specifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardFile> standard_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std> standards1 { get; set; }
        public virtual Std standard1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Std> standards11 { get; set; }
        public virtual Std standard2 { get; set; }
    }
}
