//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTaskItem
    {
        public int ID { get; set; }
        public int TaskItemID { get; set; }
        public string RequiredValue { get; set; }
        public Nullable<int> SubMethodID { get; set; }
        public string Name { get; set; }
        public string UM { get; set; }
        public Nullable<int> SubRequirementID { get; set; }
    
        public virtual SubMethod SubMethod { get; set; }
        public virtual SubRequirement SubRequirement { get; set; }
        public virtual TaskItem ParentTaskItem { get; set; }
    }
}
