//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTest
    {
        public int ID { get; set; }
        public int sub_requirementID { get; set; }
        public string Result { get; set; }
        public int testID { get; set; }
    
        public virtual SubRequirement SubRequirement { get; set; }
        public virtual Test Test { get; set; }
    }
}
