//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_items
    {
        public int ID { get; set; }
        public int taskID { get; set; }
        public int requirementID { get; set; }
    
        public virtual Requirement requirement { get; set; }
        public virtual Task task { get; set; }
    }
}
