//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskItem
    {
        public int ID { get; set; }
        public int TaskID { get; private set; }
        public int RequirementID { get; set; }
        public bool IsAssignedToReport { get; set; }
        public Nullable<int> testID { get; set; }
    
        public virtual Requirement Requirement { get; set; }
        public virtual Task Task { get; set; }
        public virtual Test Test { get; set; }
    }
}
