//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long ID { get; set; }
        public string full_name { get; set; }
        public string hashed_password { get; set; }
        public string role_list { get; set; }
        public string user_name { get; set; }
        public long personID { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
